global.cons_col=[]
cons_col["Reset"]="\x1b[0m"
cons_col["Bright"]="\x1b[1m"
cons_col["Dim"]="\x1b[2m"
cons_col["Underscore"]="\x1b[4m"
cons_col["Blink"]="\x1b[5m"
cons_col["Reverse"]="\x1b[7m"
cons_col["Hidden"]="\x1b[8m"

cons_col["FgBlack"]="\x1b[30"
cons_col["FgRed"]="\x1b[31"
cons_col["FgGreen"]="\x1b[32"
cons_col["FgYellow"]="\x1b[33"
cons_col["FgBlue"]="\x1b[34"
cons_col["FgMagenta"]="\x1b[35"
cons_col["FgCyan"]="\x1b[36"
cons_col["FgWhite"]="\x1b[37"

cons_col["BgBlack"]="\x1b[40"
cons_col["BgRed"]="\x1b[41"
cons_col["BgGreen"]="\x1b[42"
cons_col["BgYellow"]="\x1b[43"
cons_col["BgBlue"]="\x1b[44"
cons_col["BgMagenta"]="\x1b[45"
cons_col["BgCyan"]="\x1b[46"
cons_col["BgWhite"]="\x1b[47"
