console.log("                                                           _...---.._")
console.log("                                                       _.'`       -_ ``.")
console.log("                                                   .-'`                 `.")
console.log("                                                .-`                     q ;")
console.log("                                             _-`                       __  \\")
console.log("                                         .-'`                  . ' .   \\ `;/")
console.log("                                     _.-`                    /.      `._`/")
console.log("                             _...--'`                        \\_`..._")
console.log("                          .'`                         -         `'--:._")
console.log("                       .-`                           \\                  `-.")
console.log("                      .                `              `-..__.....----...., `.")
console.log("                     '                 `  '''---..-''`'              : :  : :")
console.log("                   .` -                '`.  `-.                       `'   `'")
console.log("                .-` .` '             .`'.__ ;")
console.log("            _.-` .-`   '            .")
console.log("        _.-` _.-`    .' '         .`")
console.log("(`''--'' _.-`      .'  '        .'")
console.log(" `'----''        .'  .`       .`")
console.log("               .'  .'     .-'`")
console.log("             .'   :    .-`")
console.log("             `. .`   ,`")
console.log("              .'   .'")
console.log("             '   .`")
console.log("            '  .`")
console.log("            `  '.")
console.log("            `.___;")
console.log("")